from controller import *

#SAYFA İSİMLERİ LİSTESİ
page_keys = {
    ("1") : "Anasayfa",
    ("1", "1") : "Ürün İşlemleri",
    ("1", "2") : "Stok İşlemleri",
    ("1", "3") : "Satış İşlemleri",
    ("1", "4") : "Raporlar",
    ("1", "5") : "Kullanıcı İşlemleri",
    ("1", "6") : "Ayarlar",
    ("1", "7") : "Terminal",
    ("1", "1", "1") : "Ürün Ekle",
    ("1", "1", "2") : "Ürün Sil",
    ("1", "1", "3") : "Ürün Güncelle",
    ("1", "1", "4") : "Ürün Ara",
    ("1", "1", "5") : "Tüm Ürünleri Listele",
    ("1", "2", "1") : "Stoğa Ürün Girişi",
    ("1", "2", "2") : "Stoktan Ürün Çıkışı",
    ("1", "2", "3") : "Kritik Stokları Göster",
    ("1", "2", "4") : "Stok Hareket Geçmişi",
    ("1", "3", "1") : "Satış Yap",
    ("1", "3", "2") : "Satış Geçmişi",
    ("1", "3", "3") : "İade İşlemi",
    ("1", "4", "1") : "En Çok Satan Ürüner",
    ("1", "4", "2") : "En Az Satan Ürünler",
    ("1", "4", "3") : "Günlük Satış Raporu",
    ("1", "4", "4") : "Kar Zarar Hesabı",
    ("1", "4", "5") : "Toplam Stok Değeri",
    ("1", "5", "1") : "Giriş Yap",
    ("1", "5", "2") : "Çıkış Yap",
    ("1", "5", "3") : "Kullanıcı Ekle",
    ("1", "5", "4") : "Yetkileri Görüntüle",
    ("1", "6", "1") : "Veritabanı Yedeği",
    ("1", "6", "2") : "Tema Değiştir",
    ("1", "6", "3") : "Tarih / Saat Ayarları",
    ("1", "6", "4") : "Logları Temizle",
}
#KOMUT LİSTESİ
command_list = {
    ("1", "1", "1") : new_item,
    ("1", "1", "2") : del_item,
    ("1", "1", "3") : update_item,
    ("1", "1", "4") : look_item,
    ("1", "1", "5") : item_list,
    ("1", "2", "1") : add_stock_item,
    ("1", "2", "2") : del_stock_item,
    ("1", "2", "3") : danger_stock,
    ("1", "2", "4") : transaction_history,
    ("1", "3", "1") : sales,
    ("1", "3", "2") : sales_history,
    ("1", "3", "3") : return_history,
    ("1", "4", "1") : most_sales_item,
    ("1", "4", "2") : least_sales_item,
    ("1", "4", "3") : daily_sales_report,
    ("1", "4", "4") : profit_loss,
    ("1", "4", "5") : total_worth_stok,
    ("1", "5", "1") : login,
    ("1", "5", "2") : logout,
    ("1", "5", "3") : new_user,
    ("1", "5", "4") : user_role,
    ("1", "6", "1") : backup,
    ("1", "6", "2") : theme,
    ("1", "6", "3") : date_setting,
    ("1", "6", "4") : clear_log
}